spring:
  security:
    oauth2:
      client:
        registration:
          bitbucket:
            client-id: fS8DMw9N2ZqbqLNEf6
            client-secret: VWyAntLys8hSRxD9HVzyjbrpURFD9n8E
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          bitbucket:
            user-name-attribute: username
            user-info-uri: https://api.bitbucket.org/2.0/user
            token-uri: https://bitbucket.org/site/oauth2/access_token
            authorization-uri: https://bitbucket.org/site/oauth2/authorize